name: ci
on:
  - push
  - pull_request
env:
  FORCE_COLOR: 3
concurrency:
  group: ${{ github.ref }}
  # Never cancel builds on master. This way, we can more easily figure out
  # which build/commit broke it. Replace with `true` to always cancel
  # in-progress jobs.
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  ci:
    name: CI
    # Skip tags. This 1-liner is equivalent to ~10LOC to do the same in `on`.
    if: github.event.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Dependencies
        run: npm clean-install --ignore-scripts
      - name: Build Project
        run: npx nr build
      - name: Run Tests
        run: npx nr test
