name: ci
on:
  - push
  - pull_request
env:
  FORCE_COLOR: 3
concurrency:
  # Cancel concurrent runs for the same ref.
  group: ${{ github.ref }}
  # Unless we're on master. This way, we can more easily figure out which commit
  # broke it. Replace with `true` to always cancel in-progress jobs.
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  ci:
    name: CI
    # Skip tags. This 1-liner is equivalent to ~10LOC to do the same in `on`.
    if: github.event.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: Install
        run: npm clean-install
      - name: Build
        run: npx nr build
      - name: Run Unit Tests
        run: npx nr test
